class Ascii

  def self.lore
    puts ""
    puts ""
    puts "LLLLLLLLLLL"                                                                      
    puts "L:::::::::L"                                                                     
    puts "L:::::::::L"                                                                     
    puts "LL:::::::LL"                                                                     
    puts "L:::::L                  ooooooooooo   rrrrr   rrrrrrrrr       eeeeeeeeeeee"    
    puts "L:::::L                oo:::::::::::oo r::::rrr:::::::::r    ee::::::::::::ee" 
    puts "L:::::L               o:::::::::::::::or:::::::::::::::::r  e::::::eeeee:::::ee"
    puts "L:::::L               o:::::ooooo:::::orr::::::rrrrr::::::re::::::e     e:::::e"
    puts "L:::::L               o::::o     o::::o r:::::r     r:::::re:::::::eeeee::::::e"
    puts "L:::::L               o::::o     o::::o r:::::r     rrrrrrre:::::::::::::::::e"
    puts "L:::::L               o::::o     o::::o r:::::r            e::::::eeeeeeeeeee" 
    puts "L:::::L         LLLLLLo::::o     o::::o r:::::r            e:::::::e" 
    puts "LL:::::::LLLLLLLLL:::::Lo:::::ooooo:::::o r:::::r            e::::::::e"          
    puts "L::::::::::::::::::::::Lo:::::::::::::::o r:::::r             e::::::::eeeeeeee"  
    puts "L::::::::::::::::::::::L oo:::::::::::oo  r:::::r              ee:::::::::::::e"  
    puts "LLLLLLLLLLLLLLLLLLLLLLLL   ooooooooooo    rrrrrrr                eeeeeeeeeeeeee" 
    puts ""
    puts ""
  end

  def self.skins
    puts ""
    puts ""
    puts "   SSSSSSSSSSSSSSS kkkkkkkk             iiii                                    "
    puts " SS:::::::::::::::Sk::::::k            i::::i                                   "
    puts "S:::::SSSSSS::::::Sk::::::k             iiii                                    "
    puts "S:::::S     SSSSSSSk::::::k                                                     "
    puts "S:::::S             k:::::k    kkkkkkkiiiiiiinnnn  nnnnnnnn        ssssssssss   "
    puts "S:::::S             k:::::k   k:::::k i:::::in:::nn::::::::nn    ss::::::::::s  "
    puts " S::::SSSS          k:::::k  k:::::k   i::::in::::::::::::::nn ss:::::::::::::s "
    puts "  SS::::::SSSSS     k:::::k k:::::k    i::::inn:::::::::::::::ns::::::ssss:::::s"
    puts "    SSS::::::::SS   k::::::k:::::k     i::::i  n:::::nnnn:::::n s:::::s  ssssss "
    puts "       SSSSSS::::S  k:::::::::::k      i::::i  n::::n    n::::n   s::::::s      "
    puts "            S:::::S k:::::::::::k      i::::i  n::::n    n::::n      s::::::s   "
    puts "            S:::::S k::::::k:::::k     i::::i  n::::n    n::::nssssss   s:::::s "
    puts "SSSSSSS     S:::::Sk::::::k k:::::k   i::::::i n::::n    n::::ns:::::ssss::::::s"
    puts "S::::::SSSSSS:::::Sk::::::k  k:::::k  i::::::i n::::n    n::::ns::::::::::::::s "
    puts "S:::::::::::::::SS k::::::k   k:::::k i::::::i n::::n    n::::n s:::::::::::ss  "
    puts " SSSSSSSSSSSSSSS   kkkkkkkk    kkkkkkkiiiiiiii nnnnnn    nnnnnn  sssssssssss    "
    puts ""
    puts ""
  end

  def self.abilities
     puts ""
     puts ""
     puts "                                 bbbbbbbb                                                                                                      " 
     puts "               AAA               b::::::b              iiii  lllllll   iiii          tttt            iiii                                      " 
     puts "              A:::A              b::::::b             i::::i l:::::l  i::::i      ttt:::t           i::::i                                     " 
     puts "             A:::::A             b::::::b              iiii  l:::::l   iiii       t:::::t            iiii                                      " 
     puts "            A:::::::A            b:::::b                    l:::::l              t:::::t                                                       "
     puts "           A:::::::::A           b:::::bbbbbbbbb    iiiiiii  l::::l iiiiiiittttttt:::::ttttttt    iiiiiii     eeeeeeeeeeee        ssssssssss   "
     puts "          A:::::A:::::A          b::::::::::::::bb  i:::::i  l::::l i:::::it:::::::::::::::::t    i:::::i   ee::::::::::::ee    ss::::::::::s  "
     puts "         A:::::A A:::::A         b::::::::::::::::b  i::::i  l::::l  i::::it:::::::::::::::::t     i::::i  e::::::eeeee:::::eess:::::::::::::s "
     puts "        A:::::A   A:::::A        b:::::bbbbb:::::::b i::::i  l::::l  i::::itttttt:::::::tttttt     i::::i e::::::e     e:::::es::::::ssss:::::s"
     puts "       A:::::A     A:::::A       b:::::b    b::::::b i::::i  l::::l  i::::i      t:::::t           i::::i e:::::::eeeee::::::e s:::::s  ssssss "
     puts "      A:::::AAAAAAAAA:::::A      b:::::b     b:::::b i::::i  l::::l  i::::i      t:::::t           i::::i e:::::::::::::::::e    s::::::s      "
     puts "     A:::::::::::::::::::::A     b:::::b     b:::::b i::::i  l::::l  i::::i      t:::::t           i::::i e::::::eeeeeeeeeee        s::::::s   "
     puts "    A:::::AAAAAAAAAAAAA:::::A    b:::::b     b:::::b i::::i  l::::l  i::::i      t:::::t    tttttt i::::i e:::::::e           ssssss   s:::::s "
     puts "   A:::::A             A:::::A   b:::::bbbbbb::::::bi::::::il::::::li::::::i     t::::::tttt:::::ti::::::ie::::::::e          s:::::ssss::::::s"
     puts "  A:::::A               A:::::A  b::::::::::::::::b i::::::il::::::li::::::i     tt::::::::::::::ti::::::i e::::::::eeeeeeee  s::::::::::::::s "
     puts " A:::::A                 A:::::A b:::::::::::::::b  i::::::il::::::li::::::i       tt:::::::::::tti::::::i  ee:::::::::::::e   s:::::::::::ss  "
     puts "AAAAAAA                   AAAAAAAbbbbbbbbbbbbbbbb   iiiiiiiilllllllliiiiiiii         ttttttttttt  iiiiiiii    eeeeeeeeeeeeee    sssssssssss    "
     puts ""
     puts ""
   end

   def self.tips
    puts ""
    puts ""
    puts "TTTTTTTTTTTTTTTTTTTTTTT  iiii                                      "
    puts "T:::::::::::::::::::::T i::::i                                     "
    puts "T:::::::::::::::::::::T  iiii                                      "
    puts "T:::::TT:::::::TT:::::T                                            "
    puts "TTTTTT  T:::::T  TTTTTTiiiiiiippppp   ppppppppp       ssssssssss   "
    puts "        T:::::T        i:::::ip::::ppp:::::::::p    ss::::::::::s  "
    puts "        T:::::T         i::::ip:::::::::::::::::p ss:::::::::::::s "
    puts "        T:::::T         i::::ipp::::::ppppp::::::ps::::::ssss:::::s"
    puts "        T:::::T         i::::i p:::::p     p:::::p s:::::s  ssssss "
    puts "        T:::::T         i::::i p:::::p     p:::::p   s::::::s      "
    puts "        T:::::T         i::::i p:::::p     p:::::p      s::::::s   "
    puts "        T:::::T         i::::i p:::::p    p::::::pssssss   s:::::s "
    puts "      TT:::::::TT      i::::::ip:::::ppppp:::::::ps:::::ssss::::::s"
    puts "      T:::::::::T      i::::::ip::::::::::::::::p s::::::::::::::s "
    puts "      T:::::::::T      i::::::ip::::::::::::::pp   s:::::::::::ss  "
    puts "      TTTTTTTTTTT      iiiiiiiip::::::pppppppp      sssssssssss    "
    puts "                               p:::::p                             "
    puts "                               p:::::p                             "
    puts "                              p:::::::p                            "
    puts "                              p:::::::p                            "
    puts "                              p:::::::p                            "
    puts "                              ppppppppp                            "
    puts ""
    puts ""
   end

   def self.summoner_spells
    puts ""
    puts ""
    puts " #####                                                       #####                                     "
    puts "#     # #    # #    # #    #  ####  #    # ###### #####     #     # #####  ###### #      #       ####  "
    puts "#       #    # ##  ## ##  ## #    # ##   # #      #    #    #       #    # #      #      #      #      "
    puts " #####  #    # # ## # # ## # #    # # #  # #####  #    #     #####  #    # #####  #      #       ####  "
    puts "      # #    # #    # #    # #    # #  # # #      #####           # #####  #      #      #           # "
    puts "#     # #    # #    # #    # #    # #   ## #      #   #     #     # #      #      #      #      #    # "
    puts " #####   ####  #    # #    #  ####  #    # ###### #    #     #####  #      ###### ###### ######  ####  "
    puts ""
    puts ""                           
   end
end